// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Amazon', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Amazon', async function() {
    await driver.get("https://www.amazon.com/")
    await driver.findElement(By.id("twotabsearchtextbox")).click()
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys("sneakers")
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("#p_89\\/adidas .a-icon")).click()
    await driver.findElement(By.id("a-autoid-0-announce")).click()
    await driver.findElement(By.id("s-result-sort-select_2")).click()
    {
      const element = await driver.findElement(By.css("#p_89\\/adidas .a-icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("#p_89\\/adidas .a-icon")).click()
    await driver.close()
  })
})
